baseurl = "http://rayxiaoo.github.io/static-blog/"
languageCode = "zh-cn"
title = "A static blog"

[params]
  Subtitle = "!)-.-) Hello, gfw."
  GithubID = "rayxiaoo"
  #TwitterID = ""
  #AnalyticsID = ""
  DisqusShortname = "rayxiaoo-blog"
  Summary = false  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  # FooterMsg = "Copyright Me 2016. Powered by Hugo."
